# Generated by Django 2.1.4 on 2018-12-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlistId',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
