# Generated by Django 2.1.4 on 2018-12-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0003_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(to='bpm.Track'),
        ),
    ]
